spring:
  data:
    cassandra:
      keyspace-name: main
      username: HHqKFUkKLhIScAsIAZjZROoU
      password: 9+PrM68S11FQE+hmyd1us6Omll8clU7PdLqC6-f4TWgb27J5eQNYgbTQwQbaNrwqTZRh,cDvQyZZXmGhaarmbraL6HS,woTTYNRrNvuEmu1g.3xf,pMZ17oNon0KqCql
      schema-action: create-if-not-exists


datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: 8869cae2-ac65-4360-817f-95a92a6850ea-1
  region: us-east1
  keyspace: main
  application.token: AstraCS:HHqKFUkKLhIScAsIAZjZROoU:aa4d819e806b1fc8ab7d137ae7eeaa71cfd1bc7908b0a6abf2722a40574844ab

